### ISSUE TITLE
rewrite in rust

### ISSUE THREAD

**Issue by marc-szalkiewicz-dd** [jamiealquiza/sadtomleditor#2]

**Comment by jamiealquiza** [comment]
I tested this extensively and found the following:

- Rust simply does not scale
- The proposed memory safeties fail trivial TLA+ napkin tests

Based on the above alone, I must mark this issue as invalid

**Comment by marc-szalkiewicz-dd** [comment]
But what if I told you that rust provides:

- zero-cost abstractions
- move semantics
- guaranteed memory safety
- threads without data races
- trait-based generics
- pattern matching
- type inference
- minimal runtime
- efficient C bindings

**Comment by hodgesmr** [comment]
have you considered node

**Comment by benjaminws** [comment]
rewrite in Haskell for maximum gainz 

https://wiki.haskell.org/Lifting

**Comment by jamiealquiza** [comment]
> But what if I told you that rust provides:
> 
> * zero-cost abstractions
> * move semantics
> * guaranteed memory safety
> * threads without data races
> * trait-based generics
> * pattern matching
> * type inference
> * minimal runtime
> * efficient C bindings

* zero-cost abstractions
  - The cognitive cost: everything
* move semantics
  - Pointers trivially solve this
* guaranteed memory safety
  - I admit defeat here; the amateur audience certainly benefits from this one
* threads without data races
  - same as above
* trait-based generics
  - The cognitive cost: everything
* pattern matching
  - Go has a package called regexp
* type inference
  - A Go user trivially implements this as run-time reflection inside a switch
* minimal runtime
  - Maximal writetime
* efficient C bindings
  - Go is C's cooler step-son with the corvette
